/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author adem_
 */
class Hatalar // Polimorhism başlangıcı
{

    private String hataAdi;

    public Hatalar(String hataAdi) {
        this.hataAdi = hataAdi;
    }

    public String getHataAdi() {
        return hataAdi;
    }

    public void setHataAdi(String hataAdi) {
        this.hataAdi = hataAdi;
    }

    public String hataMesaji() {
        return "Uyarı farklı bir hata oluştu !";
    }
}

class girisHatasi extends Hatalar {

    public girisHatasi(String hataAdi) {
        super(hataAdi);
    }

    public String hataMesaji() {
        return this.getHataAdi();
    }

}

public class Admin extends javax.swing.JFrame {

    Connection connection;
    ResultSet resultSet;
    PreparedStatement preparedStatement;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel3.setBackground(new java.awt.Color(0, 0, 0, 200));
        connection = DBConnect.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtTCNo = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnSifreUnuttum = new javax.swing.JButton();
        btnGiris = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnKayit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.setAutoscrolls(true);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\exit.png")); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Magneto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Copyright © 2020-2021 Adem KARADENIZ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 350, 30));

        lblUsername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 153, 0));
        lblUsername.setText("TC Kimlik No :");
        jPanel3.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 101, -1));

        txtTCNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTCNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTCNoActionPerformed(evt);
            }
        });
        jPanel3.add(txtTCNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 310, -1));

        lblPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 153, 0));
        lblPassword.setText("Parola :");
        jPanel3.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 73, -1));

        txtPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 310, -1));

        btnSifreUnuttum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSifreUnuttum.setText("Şifremi Unuttum");
        btnSifreUnuttum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSifreUnuttumActionPerformed(evt);
            }
        });
        jPanel3.add(btnSifreUnuttum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        btnGiris.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGiris.setText("Giriş Yap");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });
        jPanel3.add(btnGiris, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 150, -1));

        jLabel3.setFont(new java.awt.Font("Juice ITC", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("BLACKSEA KÜTÜPHANESİ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 380, 40));

        btnKayit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKayit.setText("Kayıt Ol");
        btnKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitActionPerformed(evt);
            }
        });
        jPanel3.add(btnKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 150, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\arkaplan-fotograflar-3.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(600, 750));
        jLabel1.setPreferredSize(new java.awt.Dimension(870, 750));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        setSize(new java.awt.Dimension(698, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        try {
            preparedStatement = connection.prepareCall("Select * from Yoneticiler");
            resultSet = preparedStatement.executeQuery();

            while (resultSet.next()) {
                if (resultSet.getString("TCNo").equals(txtTCNo.getText()) && resultSet.getString("Password").equals(txtPassword.getText())) {

                    AnaSayfa anaSayfa = new AnaSayfa();
                    anaSayfa.setVisible(true);
                    setVisible(false);
                } else {

                    Hatalar hataver = new girisHatasi("Kullanıcı TC No veya Şifre Yanlış!");

                    JOptionPane.showMessageDialog(null, hataver.hataMesaji());
                }

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnGirisActionPerformed

    private void btnSifreUnuttumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSifreUnuttumActionPerformed
        SifremiUnuttum forgotPassword = new SifremiUnuttum();
        forgotPassword.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_btnSifreUnuttumActionPerformed

    private void txtTCNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTCNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTCNoActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitActionPerformed
        KayitOl kayitOl = new KayitOl();
        kayitOl.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnKayitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
//                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnKayit;
    private javax.swing.JButton btnSifreUnuttum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTCNo;
    // End of variables declaration//GEN-END:variables
}
