/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adem_
 */
public class AnaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form AnaSayfa
     */
    public AnaSayfa() {
        initComponents();
        //Çerçeve kaybetmek için kullandığım kod.
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel5.setBackground(new java.awt.Color(0, 0, 0, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnKitapGuncelle = new javax.swing.JButton();
        btnGeriBırak1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAddUsers = new javax.swing.JButton();
        btnOgrenciSil = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnKitapOduncVer = new javax.swing.JButton();
        btnGeriBırak = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAddBook = new javax.swing.JButton();
        btnStatics = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnKitapAra = new javax.swing.JButton();
        btnKitapSil = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Güncelleme İşlemleri", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKitapGuncelle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKitapGuncelle.setText("Kitap Güncelle");
        btnKitapGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapGuncelleActionPerformed(evt);
            }
        });
        jPanel4.add(btnKitapGuncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 280, -1));

        btnGeriBırak1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGeriBırak1.setText("Öğrenci Güncelle");
        btnGeriBırak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriBırak1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnGeriBırak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 320, -1));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 770, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Öğrenci İşlemleri", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddUsers.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddUsers.setText("Öğrenci Ekle");
        btnAddUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUsersActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 280, -1));

        btnOgrenciSil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOgrenciSil.setText("Öğrenci Sil");
        btnOgrenciSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrenciSilActionPerformed(evt);
            }
        });
        jPanel2.add(btnOgrenciSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 320, -1));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 770, 90));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Kitap - Öğrenci İşlemleri", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKitapOduncVer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKitapOduncVer.setText("Kitap Ödünç Ver");
        btnKitapOduncVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapOduncVerActionPerformed(evt);
            }
        });
        jPanel3.add(btnKitapOduncVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 280, -1));

        btnGeriBırak.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGeriBırak.setText("Kitap İade Et");
        btnGeriBırak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriBırakActionPerformed(evt);
            }
        });
        jPanel3.add(btnGeriBırak, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 320, -1));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 770, 80));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Kitap İşlemleri", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddBook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddBook.setText("Kitap Ekle");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 50, 150, -1));

        btnStatics.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnStatics.setText("Kitap Listeleri");
        btnStatics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaticsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStatics, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 143, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 35, -1, -1));

        btnKitapAra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKitapAra.setText("Kütüphanede Kitap Ara");
        btnKitapAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapAraActionPerformed(evt);
            }
        });
        jPanel1.add(btnKitapAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 200, -1));

        btnKitapSil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKitapSil.setText("Kitap Sil");
        btnKitapSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapSilActionPerformed(evt);
            }
        });
        jPanel1.add(btnKitapSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 150, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 770, 110));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\as.png")); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 30, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\exit.png")); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel12.setMaximumSize(new java.awt.Dimension(35, 30));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\arkaplan-900.jpg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        setSize(new java.awt.Dimension(850, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed

        KitapEkle kitapEkle = new KitapEkle();
        kitapEkle.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnStaticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaticsActionPerformed

        KitapListesi kitapListesi = new KitapListesi();
        kitapListesi.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_btnStaticsActionPerformed

    private void btnAddUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUsersActionPerformed

        OgrenciEkle ogrenciEkle = new OgrenciEkle();
        ogrenciEkle.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_btnAddUsersActionPerformed

    private void btnOgrenciSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrenciSilActionPerformed

        OgrenciSil ogrenciSil = new OgrenciSil();
        ogrenciSil.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnOgrenciSilActionPerformed

    private void btnKitapSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapSilActionPerformed

        KitapSil kitapSil = new KitapSil();
        kitapSil.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnKitapSilActionPerformed

    private void btnKitapOduncVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapOduncVerActionPerformed

        KitapOduncVer kitapOduncVer = new KitapOduncVer();
        kitapOduncVer.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnKitapOduncVerActionPerformed

    private void btnGeriBırakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriBırakActionPerformed

        KitapTeslimAl kitapTeslimAl = new KitapTeslimAl();
        kitapTeslimAl.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnGeriBırakActionPerformed

    private void btnKitapAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapAraActionPerformed

        KitapAra kitapAra = new KitapAra();
        kitapAra.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_btnKitapAraActionPerformed

    private void btnKitapGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapGuncelleActionPerformed

        KitapGuncelle kitapGuncelle = new KitapGuncelle();
        kitapGuncelle.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnKitapGuncelleActionPerformed

    private void btnGeriBırak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriBırak1ActionPerformed

        OgrenciGuncelle ogrenciGuncelle = new OgrenciGuncelle();
        ogrenciGuncelle.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnGeriBırak1ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        Admin admin = new Admin();
        admin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnAddUsers;
    private javax.swing.JButton btnGeriBırak;
    private javax.swing.JButton btnGeriBırak1;
    private javax.swing.JButton btnKitapAra;
    private javax.swing.JButton btnKitapGuncelle;
    private javax.swing.JButton btnKitapOduncVer;
    private javax.swing.JButton btnKitapSil;
    private javax.swing.JButton btnOgrenciSil;
    private javax.swing.JButton btnStatics;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
