
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adem_
 */
public class KitapTeslimAl extends javax.swing.JFrame {

    KitaplarBaseManager kitaplarBaseManager = new KitaplarBaseManager();
    Connection connection;
    ResultSet resultSet;
    PreparedStatement preparedStatement;

    /**
     * Creates new form KitapTeslimAl
     */
    public KitapTeslimAl() {
        initComponents();
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel3.setBackground(new java.awt.Color(0, 0, 0, 200));
        connection = DBConnect.getConnection();
    }

    public void txtClear() {
        cmbxBarkodNo.removeAllItems();
        txtKitapAdi.setText(null);
        txtYazar.setText(null);
        txtYayinevi.setText(null);
        txtTur.setText(null);
        txtSayfa.setText(null);
        txtOgrTc.setText(null);
        txtAdSoyad.setText(null);
        txtCinsiyet.setText(null);
        txtEmail.setText(null);
        txtTelNo.setText(null);
        txtOduncTarih.setText(null);
        txtDonusTarih.setDate(null);
    }

    public void txtKitapClear() {
        txtKitapAdi.setText(null);
        txtYazar.setText(null);
        txtYayinevi.setText(null);
        txtTur.setText(null);
        txtSayfa.setText(null);
    }

    public void ogrenciBilgiDoldur(String ogrenciTCNo) {
        String sql = "Select *from Ogrenciler where TCNo=? ";
        try {
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, ogrenciTCNo);
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                String ekle1 = resultSet.getString("AdSoyad");
                txtAdSoyad.setText(ekle1);
                String ekle2 = resultSet.getString("Email");
                txtEmail.setText(ekle2);
                String ekle3 = resultSet.getString("Cinsiyet");
                txtCinsiyet.setText(ekle3);
                String ekle4 = resultSet.getString("TelNo");
                txtTelNo.setText(ekle4);
                resultSet.close();
                preparedStatement.close();
            } else {
                JOptionPane.showMessageDialog(null, "Öğrenci Bulunamadı");
                txtClear();
            }
            resultSet.close();
            preparedStatement.close();
        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, exception);

        }

    }

    public void emanetlerdenSil(String barkodNo) {
        String sql = "Delete from EmanetKitaplar where KitapBarkodNo=?";
        try {

            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, barkodNo);
            preparedStatement.execute();

        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, sql);
        }

    }

    public void emanetGecmisineEkle() {
        String sql = "Insert into EmanetGecmis(KitapBarkodNo,OgrenciTCNo,OduncTarih,DonusTarih,Status,CreateOrModifyDate)values(?,?,?,?,?,?)";
        try {

            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, cmbxBarkodNo.getSelectedItem().toString());
            preparedStatement.setString(2, txtOgrTc.getText());
            preparedStatement.setString(3, txtOduncTarih.getText());
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            preparedStatement.setString(4, formatter.format(txtDonusTarih.getDate()));
            preparedStatement.setString(5, "1");
            preparedStatement.setString(6, GeneralAppService.createNowDate().toString());
            preparedStatement.execute();

        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, exception);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDonusTarih = new com.toedter.calendar.JDateChooser();
        txtTeslimAl = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtSayfa = new javax.swing.JTextField();
        txtAdSoyad = new javax.swing.JTextField();
        txtYazar = new javax.swing.JTextField();
        txtYayinevi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtKitapAdi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTelNo = new javax.swing.JTextField();
        txtCinsiyet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAra = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOgrTc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtOduncTarih = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTur = new javax.swing.JTextField();
        cmbxBarkodNo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 153, 0));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("   İade Tarihi");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 96, 25));

        txtDonusTarih.setDateFormatString("yyyy-MM-dd");
        txtDonusTarih.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtDonusTarih, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 200, 25));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 330, 50));

        txtTeslimAl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTeslimAl.setText("TESLİM AL");
        txtTeslimAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeslimAlActionPerformed(evt);
            }
        });
        jPanel3.add(txtTeslimAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 300, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\asd.png")); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel15.setMaximumSize(new java.awt.Dimension(35, 30));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\as.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\exit.png")); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Kitap Teslim Paneli", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSayfa.setEditable(false);
        txtSayfa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtSayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 221, 158, -1));

        txtAdSoyad.setEditable(false);
        txtAdSoyad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtAdSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 78, 160, -1));

        txtYazar.setEditable(false);
        txtYazar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtYazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 115, 158, -1));

        txtYayinevi.setEditable(false);
        txtYayinevi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtYayinevi, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 153, 158, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("Cinsiyet");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 122, -1, -1));

        txtKitapAdi.setEditable(false);
        txtKitapAdi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtKitapAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 78, 158, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Sayfa Sayısı");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 224, -1, -1));

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 160, 160, -1));

        txtTelNo.setEditable(false);
        txtTelNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtTelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 200, 160, -1));

        txtCinsiyet.setEditable(false);
        txtCinsiyet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtCinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 119, 160, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Kitap Adı");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 81, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Yazarı");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 118, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("TC Kimlik No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 46, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Yayınevi");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 156, -1, -1));

        btnAra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAra.setText("Ara");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });
        jPanel1.add(btnAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 42, 78, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Telefon No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 203, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Kitap Barkod No");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 46, 110, -1));

        txtOgrTc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtOgrTc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOgrTcKeyReleased(evt);
            }
        });
        jPanel1.add(txtOgrTc, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 43, 160, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Öğrenci Adı Soyadı");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 81, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("E-Mail");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 166, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("Ödünç Alma Tarihi");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 266, -1, -1));

        txtOduncTarih.setEditable(false);
        txtOduncTarih.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtOduncTarih, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 263, 150, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("Tür");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 190, -1, -1));

        txtTur.setEditable(false);
        txtTur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 187, 158, -1));

        cmbxBarkodNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbxBarkodNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxBarkodNoİtemStateChanged(evt);
            }
        });
        jPanel1.add(cmbxBarkodNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 43, 160, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 740, 300));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 485));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\arkaplan-800.jpg")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 484));

        setSize(new java.awt.Dimension(800, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeslimAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeslimAlActionPerformed
        try {
            emanetlerdenSil(cmbxBarkodNo.getSelectedItem().toString());
            //KitaplarBaseManager sınıfındaki ekleme metodunu kısaca buradan çalıştırıyorum.
            kitaplarBaseManager.insertBook(cmbxBarkodNo.getSelectedItem().toString(), txtKitapAdi.getText(), txtYazar.getText(), txtYayinevi.getText(), txtTur.getText(), txtSayfa.getText(), "1", GeneralAppService.createNowDate().toString());
            emanetGecmisineEkle();
            JOptionPane.showMessageDialog(null, "Kitap Teslim Alındı.");
            txtClear();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Teslim alınma sırasında hata oluştu !");
        }

    }//GEN-LAST:event_txtTeslimAlActionPerformed

    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
        cmbxBarkodNo.removeAllItems();
        String sql = "Select * from EmanetKitaplar where OgrenciTCNo=? ";
        try {
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, txtOgrTc.getText());
            resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                cmbxBarkodNo.addItem(resultSet.getString("KitapBarkodNo"));
            }
            ogrenciBilgiDoldur(txtOgrTc.getText());
            resultSet.close();
            preparedStatement.close();
        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, exception);

        } finally {
            try {
                preparedStatement.close();
                resultSet.close();
            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, exception);
            }
        }

    }//GEN-LAST:event_btnAraActionPerformed

    private void cmbxBarkodNoİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxBarkodNoİtemStateChanged
        // TODO add your handling code here:

        ResultSet resultSetKitap;
        PreparedStatement preparedStatementKitap;
        String sql = "Select * from EmanetKitaplar where KitapBarkodNo=?";
        try {
            txtKitapClear();
            preparedStatementKitap = connection.prepareStatement(sql);
            preparedStatementKitap.setString(1, (String) cmbxBarkodNo.getSelectedItem());
            resultSetKitap = preparedStatementKitap.executeQuery();
            if (resultSetKitap.next()) {
                String ekle1 = resultSetKitap.getString("KitapAdi");
                txtKitapAdi.setText(ekle1);
                String ekle2 = resultSetKitap.getString("Yazar");
                txtYazar.setText(ekle2);
                String ekle3 = resultSetKitap.getString("Yayinevi");
                txtYayinevi.setText(ekle3);
                String ekle4 = resultSetKitap.getString("Tur");
                txtTur.setText(ekle4);
                String ekle5 = resultSetKitap.getString("Sayfa");
                txtSayfa.setText(ekle5);
                String ekle6 = resultSetKitap.getString("OduncTarih");
                txtOduncTarih.setText(ekle6);
                resultSetKitap.close();
                preparedStatementKitap.close();
            } else {
                resultSetKitap.close();
                preparedStatementKitap.close();
            }
        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, exception);
        }
    }//GEN-LAST:event_cmbxBarkodNoİtemStateChanged

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        GeneralAppService.backActionAnaSayfa();
        setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked

        Admin admin = new Admin();
        admin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void txtOgrTcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOgrTcKeyReleased
        txtAdSoyad.setText(null);
        txtCinsiyet.setText(null);
        txtEmail.setText(null);
        txtTelNo.setText(null);
    }//GEN-LAST:event_txtOgrTcKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapTeslimAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapTeslimAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapTeslimAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapTeslimAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapTeslimAl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAra;
    private javax.swing.JComboBox<String> cmbxBarkodNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAdSoyad;
    private javax.swing.JTextField txtCinsiyet;
    private com.toedter.calendar.JDateChooser txtDonusTarih;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKitapAdi;
    private javax.swing.JTextField txtOduncTarih;
    private javax.swing.JTextField txtOgrTc;
    private javax.swing.JTextField txtSayfa;
    private javax.swing.JTextField txtTelNo;
    private javax.swing.JButton txtTeslimAl;
    private javax.swing.JTextField txtTur;
    private javax.swing.JTextField txtYayinevi;
    private javax.swing.JTextField txtYazar;
    // End of variables declaration//GEN-END:variables
}
