
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adem_
 */
public class KitapOduncVer extends javax.swing.JFrame {

    KitaplarBaseManager kitaplarBaseManager = new KitaplarBaseManager();
    Connection connection;
    ResultSet resultSet;
    PreparedStatement preparedStatement;

    /**
     * Creates new form KitapOduncVer
     */
    public KitapOduncVer() {
        initComponents();
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel4.setBackground(new java.awt.Color(0, 0, 0, 200));
        connection = DBConnect.getConnection();
    }

    public void txtClear() {
        txtBarkodNo.setText(null);
        txtKitapAdi.setText(null);
        txtKitapYazar.setText(null);
        txtKitapYayinevi.setText(null);
        txtTur.setText(null);
        txtKitapSayfa.setText(null);
        txtOgrTc.setText(null);
        txtAdSoyad.setText(null);
        txtCinsiyet.setText(null);
        txtEmail.setText(null);
        txtTelNo.setText(null);
        txtOduncTarih.setDate(null);
    }

    public void txtKitapClear() {
        txtBarkodNo.setText(null);
        txtKitapAdi.setText(null);
        txtKitapYazar.setText(null);
        txtKitapYayinevi.setText(null);
        txtTur.setText(null);
        txtKitapSayfa.setText(null);
    }

    public void txtOgrClear() {
        txtOgrTc.setText(null);
        txtAdSoyad.setText(null);
        txtCinsiyet.setText(null);
        txtEmail.setText(null);
        txtTelNo.setText(null);
    }

    public void kitapTableDelete(String barkodNo) {
        if (txtBarkodNo.getText() != null) {
            kitaplarBaseManager.deleteBook(txtBarkodNo.getText());
        }

    }

    public boolean kitapEmanettemi(String barkodNo) {
        String sql = "Select * from EmanetKitaplar where KitapBarkodNo=?";
        try {
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, barkodNo);
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                return true;
            } else {
                return false;
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, exception);
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnOduncAl = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtOduncTarih = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCinsiyet = new javax.swing.JTextField();
        txtTelNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAramaOgrenci = new javax.swing.JButton();
        txtOgrTc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAdSoyad = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtKitapYazar = new javax.swing.JTextField();
        txtBarkodNo = new javax.swing.JTextField();
        txtKitapSayfa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKitapYayinevi = new javax.swing.JTextField();
        btnAramaKitap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKitapAdi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTur = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\exit.png")); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOduncAl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOduncAl.setText("ÖDÜNÇ VER");
        btnOduncAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduncAlActionPerformed(evt);
            }
        });
        jPanel4.add(btnOduncAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 230, 40));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("Ödünç Alma Tarihi(GG.AA.YYYY)");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 12, 230, 30));

        txtOduncTarih.setDateFormatString("yyyy-MM-dd");
        txtOduncTarih.setMinimumSize(new java.awt.Dimension(27, 25));
        jPanel3.add(txtOduncTarih, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 11, 150, 30));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 390, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Öğrenci Arama", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Ad Soyad");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 89, -1, -1));

        txtCinsiyet.setEditable(false);
        txtCinsiyet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtCinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 133, 159, -1));

        txtTelNo.setEditable(false);
        txtTelNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtTelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 215, 159, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("E-Mail");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 177, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Cinsiyet");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 136, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("TC Kimlik No");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 46, -1, -1));

        btnAramaOgrenci.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAramaOgrenci.setText("Ara");
        btnAramaOgrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAramaOgrenciActionPerformed(evt);
            }
        });
        jPanel2.add(btnAramaOgrenci, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 42, -1, -1));

        txtOgrTc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtOgrTc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOgrTcKeyReleased(evt);
            }
        });
        jPanel2.add(txtOgrTc, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 43, 159, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Telefon No");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 218, -1, -1));

        txtAdSoyad.setEditable(false);
        txtAdSoyad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtAdSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 86, 159, -1));

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 174, 159, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 360, 270));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Kitap Arama", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20), new java.awt.Color(255, 153, 51))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Yayınevi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 149, -1, -1));

        txtKitapYazar.setEditable(false);
        txtKitapYazar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtKitapYazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 112, 170, -1));

        txtBarkodNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtBarkodNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarkodNoKeyReleased(evt);
            }
        });
        jPanel1.add(txtBarkodNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 43, 170, -1));

        txtKitapSayfa.setEditable(false);
        txtKitapSayfa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtKitapSayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 210, 170, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Yazarı");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 115, -1, -1));

        txtKitapYayinevi.setEditable(false);
        txtKitapYayinevi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtKitapYayinevi, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 146, 170, -1));

        btnAramaKitap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAramaKitap.setText("Ara");
        btnAramaKitap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAramaKitapActionPerformed(evt);
            }
        });
        jPanel1.add(btnAramaKitap, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 42, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Kitap Adı");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 78, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Sayfa Sayısı");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 213, -1, -1));

        txtKitapAdi.setEditable(false);
        txtKitapAdi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtKitapAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 78, 170, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Kitap Barkod No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 46, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("Tür");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 183, -1, -1));

        txtTur.setEditable(false);
        txtTur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 180, 170, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 390, 270));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\asd.png")); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel15.setMaximumSize(new java.awt.Dimension(35, 30));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\as.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 474));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\arkaplan-800.jpg")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 474));

        setSize(new java.awt.Dimension(801, 474));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAramaOgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAramaOgrenciActionPerformed
        String sql = "Select *from Ogrenciler where TCNo=? ";
        try {
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, txtOgrTc.getText());
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                String ekle1 = resultSet.getString("AdSoyad");
                txtAdSoyad.setText(ekle1);
                String ekle2 = resultSet.getString("Email");
                txtEmail.setText(ekle2);
                String ekle3 = resultSet.getString("Cinsiyet");
                txtCinsiyet.setText(ekle3);
                String ekle4 = resultSet.getString("TelNo");
                txtTelNo.setText(ekle4);
                resultSet.close();
                preparedStatement.close();
            } else {
                JOptionPane.showMessageDialog(null, "Öğrenci Bulunamadı");
                txtOgrClear();
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, exception);
        } finally {
            try {
                resultSet.close();
                preparedStatement.close();
            } catch (Exception exception) {
                JOptionPane.showMessageDialog(null, exception);
            }

        }
    }//GEN-LAST:event_btnAramaOgrenciActionPerformed

    private void btnOduncAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduncAlActionPerformed

        String sql = "Insert into EmanetKitaplar(OgrenciTCNo,KitapBarkodNo,KitapAdi,Yazar,Yayinevi,Tur,Sayfa,OduncTarih,Status,CreateOrModifyDate) values(?,?,?,?,?,?,?,?,?,?) ";
        try {
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, txtOgrTc.getText());
            preparedStatement.setString(2, txtBarkodNo.getText());
            preparedStatement.setString(3, txtKitapAdi.getText());
            preparedStatement.setString(4, txtKitapYazar.getText());
            preparedStatement.setString(5, txtKitapYayinevi.getText());
            preparedStatement.setString(6, txtTur.getText());
            preparedStatement.setString(7, txtKitapSayfa.getText());
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            preparedStatement.setString(8, formatter.format(txtOduncTarih.getDate()));
            preparedStatement.setString(9, "1");
            preparedStatement.setString(10, GeneralAppService.createNowDate().toString());
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null, "Kitap Emanet Olarak Verildi.");
            kitapTableDelete(txtBarkodNo.getText());
            txtClear();

        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Seçili Kitap Başka Bir Öğrencidedir");
        }
    }//GEN-LAST:event_btnOduncAlActionPerformed

    private void btnAramaKitapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAramaKitapActionPerformed
        if (kitapEmanettemi(txtBarkodNo.getText()) != true) {
            String sql = "Select * from Kitaplar where BarkodNo=?";
            try {
                preparedStatement = connection.prepareStatement(sql);
                preparedStatement.setString(1, txtBarkodNo.getText());
                resultSet = preparedStatement.executeQuery();
                if (resultSet.next()) {
                    String ekle1 = resultSet.getString("KitapAdi");
                    txtKitapAdi.setText(ekle1);
                    String ekle2 = resultSet.getString("Yazar");
                    txtKitapYazar.setText(ekle2);
                    String ekle3 = resultSet.getString("Yayinevi");
                    txtKitapYayinevi.setText(ekle3);
                    String ekle4 = resultSet.getString("Tur");
                    txtTur.setText(ekle4);
                    String ekle5 = resultSet.getString("Sayfa");
                    txtKitapSayfa.setText(ekle5);
                    resultSet.close();
                    preparedStatement.close();
                } else {
                    JOptionPane.showMessageDialog(null, "Kitap Adı Bulunamadı");
                    txtKitapClear();
                }
            } catch (Exception exception) {
                JOptionPane.showMessageDialog(null, exception);
            } finally {
                try {
                    resultSet.close();
                    preparedStatement.close();
                } catch (Exception exception) {
                    JOptionPane.showMessageDialog(null, exception);
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Kitap şu anda emanetler listesinde gözüküyor !");
            txtKitapClear();
        }

    }//GEN-LAST:event_btnAramaKitapActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        GeneralAppService.backActionAnaSayfa();
        setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked

        Admin admin = new Admin();
        admin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void txtBarkodNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarkodNoKeyReleased
        txtKitapAdi.setText(null);
        txtKitapYazar.setText(null);
        txtKitapYayinevi.setText(null);
        txtTur.setText(null);
        txtKitapSayfa.setText(null);
    }//GEN-LAST:event_txtBarkodNoKeyReleased

    private void txtOgrTcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOgrTcKeyReleased
        txtAdSoyad.setText(null);
        txtCinsiyet.setText(null);
        txtEmail.setText(null);
        txtTelNo.setText(null);
    }//GEN-LAST:event_txtOgrTcKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapOduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapOduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapOduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapOduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapOduncVer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAramaKitap;
    private javax.swing.JButton btnAramaOgrenci;
    private javax.swing.JButton btnOduncAl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtAdSoyad;
    private javax.swing.JTextField txtBarkodNo;
    private javax.swing.JTextField txtCinsiyet;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKitapAdi;
    private javax.swing.JTextField txtKitapSayfa;
    private javax.swing.JTextField txtKitapYayinevi;
    private javax.swing.JTextField txtKitapYazar;
    private com.toedter.calendar.JDateChooser txtOduncTarih;
    private javax.swing.JTextField txtOgrTc;
    private javax.swing.JTextField txtTelNo;
    private javax.swing.JTextField txtTur;
    // End of variables declaration//GEN-END:variables
}
