
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adem_
 */
public class KitapGuncelle extends javax.swing.JFrame {

    Connection connection;
    ResultSet resultSet;
    PreparedStatement preparedStatement;
    KitaplarBaseManager kitaplarBaseManager = new KitaplarBaseManager();

    /**
     * Creates new form KitapGuncelle
     */
    public KitapGuncelle() {
        initComponents();
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 200));
        connection = DBConnect.getConnection();
    }

    public boolean kitapSorgula(String barkodNo) {
        String sql = "Select * from Kitaplar where BarkodNo=?";
        try {
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, barkodNo);
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                return true;
            } else {
                return false;
            }
        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, exception);
            return false;
        }
    }

    public void txtEditable(boolean ozellik) {
        txtKitapAdi.setEditable(ozellik);
        txtYazar.setEditable(ozellik);
        txtYayinevi.setEditable(ozellik);
        txtTur.setEditable(ozellik);
        txtSayfa.setEditable(ozellik);
    }

    public void txtClear() {
        txtBarkodNo.setText(null);
        txtKitapAdi.setText(null);
        txtYazar.setText(null);
        txtYayinevi.setText(null);
        txtTur.setText(null);
        txtSayfa.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSayfa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtYazar = new javax.swing.JTextField();
        txtBarkodNo = new javax.swing.JTextField();
        txtKitapAdi = new javax.swing.JTextField();
        txtYayinevi = new javax.swing.JTextField();
        btnKitapArama = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnKitapGuncelle = new javax.swing.JButton();
        txtTur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\asd.png")); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel15.setMaximumSize(new java.awt.Dimension(35, 30));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Kitap Güncelleme Paneli", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Yazarı");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 129, -1, -1));

        txtSayfa.setEditable(false);
        txtSayfa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtSayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 249, 240, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Kitap Adı");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 88, 81, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Sayfa Sayısı");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 255, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Kitap Barkod No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 43, 118, 22));

        txtYazar.setEditable(false);
        txtYazar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtYazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 126, 240, -1));

        txtBarkodNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtBarkodNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarkodNoKeyReleased(evt);
            }
        });
        jPanel1.add(txtBarkodNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 43, 240, -1));

        txtKitapAdi.setEditable(false);
        txtKitapAdi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtKitapAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 85, 240, -1));

        txtYayinevi.setEditable(false);
        txtYayinevi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtYayinevi, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 167, 240, -1));

        btnKitapArama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKitapArama.setText("ARA");
        btnKitapArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapAramaActionPerformed(evt);
            }
        });
        jPanel1.add(btnKitapArama, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 93, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Yayınevi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 170, -1, -1));

        btnKitapGuncelle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKitapGuncelle.setText("GÜNCELLE");
        btnKitapGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapGuncelleActionPerformed(evt);
            }
        });
        jPanel1.add(btnKitapGuncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 180, -1));

        txtTur.setEditable(false);
        txtTur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 208, 240, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Tür");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 211, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 55, 510, 350));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\as.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\exit.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\arkaplan-800.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 440));

        setSize(new java.awt.Dimension(578, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKitapAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapAramaActionPerformed
        String sql = "Select * from Kitaplar where BarkodNo=?";
        try {
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, txtBarkodNo.getText());
            resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                String ekle1 = resultSet.getString("KitapAdi");
                txtKitapAdi.setText(ekle1);
                String ekle2 = resultSet.getString("Yazar");
                txtYazar.setText(ekle2);
                String ekle3 = resultSet.getString("Yayinevi");
                txtYayinevi.setText(ekle3);
                String ekle4 = resultSet.getString("Tur");
                txtTur.setText(ekle4);
                String ekle5 = resultSet.getString("Sayfa");
                txtSayfa.setText(ekle5);
                resultSet.close();
                preparedStatement.close();
                txtEditable(true);
            } else {

                JOptionPane.showMessageDialog(null, "Kitap Bulunamadı !");
                txtEditable(false);
                txtClear();

            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, exception);
        } finally {
            try {
                resultSet.close();
                preparedStatement.close();
            } catch (Exception exception) {
                JOptionPane.showMessageDialog(null, exception);
            }

        }
    }//GEN-LAST:event_btnKitapAramaActionPerformed

    private void btnKitapGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapGuncelleActionPerformed
        if (kitapSorgula(txtBarkodNo.getText()) != false) {
            try {
                if (txtBarkodNo.getText().length() != 0) {
                    if (txtKitapAdi.getText().length() != 0 && txtYazar.getText().length() != 0) {
                        //KitaplarBaseManager classındaki hazırladığım kodu kullanıyorum
                        kitaplarBaseManager.updateBook(txtBarkodNo.getText(), txtKitapAdi.getText(), txtYazar.getText(), txtYayinevi.getText(), txtTur.getText(), txtSayfa.getText(), "1", GeneralAppService.createNowDate().toString());
                        JOptionPane.showMessageDialog(null, "Kitap Güncellendi");
                        txtClear();
                    } else {
                        JOptionPane.showMessageDialog(null, "Kitap Adı ve Yazar Kısmı Boş Geçilemez !");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Barkod No Boş Geçilemez !");
                }

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(null, exception);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kitap listesinde böyle bir kitap bulunamadı !");
            txtClear();
        }
    }//GEN-LAST:event_btnKitapGuncelleActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        GeneralAppService.backActionAnaSayfa();
        setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        Admin admin = new Admin();
        admin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtBarkodNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarkodNoKeyReleased
        txtKitapAdi.setText(null);
        txtYazar.setText(null);
        txtYayinevi.setText(null);
        txtTur.setText(null);
        txtSayfa.setText(null);
    }//GEN-LAST:event_txtBarkodNoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKitapArama;
    private javax.swing.JButton btnKitapGuncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtBarkodNo;
    private javax.swing.JTextField txtKitapAdi;
    private javax.swing.JTextField txtSayfa;
    private javax.swing.JTextField txtTur;
    private javax.swing.JTextField txtYayinevi;
    private javax.swing.JTextField txtYazar;
    // End of variables declaration//GEN-END:variables
}
