
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adem_
 */
public class OgrenciSil extends javax.swing.JFrame {

    OgrencilerBaseManager ogrencilerBaseManager = new OgrencilerBaseManager();
    Connection connection;
    ResultSet resultSet;
    PreparedStatement preparedStatement;

    /**
     * Creates new form OgrenciSil
     */
    public OgrenciSil() {
        initComponents();
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 200));
        connection = DBConnect.getConnection();
    }

    public boolean ogrenciSorgula(String TCNo) {
        String sql = "Select * from Ogrenciler where TCNo=?";
        try {
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, TCNo);
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                return true;
            } else {
                return false;
            }
        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, exception);
            return false;
        }
    }

    public void txtClear() {
        txtOgrTc.setText(null);
        txtOgrAdSoyad.setText(null);
        txtCinsiyet.setText(null);
        txtEmail.setText(null);
        txtTelefonNo.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSil = new javax.swing.JButton();
        btnOgrenciAra = new javax.swing.JButton();
        txtOgrTc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOgrAdSoyad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefonNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCinsiyet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Öğrenci Silme Paneli", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });
        jPanel1.add(btnSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 190, 30));

        btnOgrenciAra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOgrenciAra.setText("ARA");
        btnOgrenciAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrenciAraActionPerformed(evt);
            }
        });
        jPanel1.add(btnOgrenciAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 42, 80, -1));

        txtOgrTc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtOgrTc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOgrTcKeyReleased(evt);
            }
        });
        jPanel1.add(txtOgrTc, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 43, 230, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Telefon No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, -1, -1));

        txtOgrAdSoyad.setEditable(false);
        txtOgrAdSoyad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtOgrAdSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 78, 230, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Cinsiyet");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 115, -1, -1));

        txtTelefonNo.setEditable(false);
        txtTelefonNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtTelefonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 180, 230, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("TC Kimlik No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 46, -1, -1));

        txtCinsiyet.setEditable(false);
        txtCinsiyet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtCinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 112, 230, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Ad Soyad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 81, -1, -1));

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 146, 230, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("E-Mail");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 146, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 460, 270));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\asd.png")); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel15.setMaximumSize(new java.awt.Dimension(35, 30));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\as.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\exit.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 350));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\arkaplan-fotograflar-3.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 350));

        setSize(new java.awt.Dimension(519, 348));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        if (ogrenciSorgula(txtOgrTc.getText()) != false) {

            if (txtOgrTc.getText() != null) {
                ogrencilerBaseManager.deleteStudent(txtOgrTc.getText());
                JOptionPane.showMessageDialog(null, "Öğrenci Silindi");
                txtClear();
            } else {
                JOptionPane.showMessageDialog(null, "Öğrenci Tc No Boş Geçilemez !");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Öğrenci listesinde böyle bir öğrenci bulunamadı !");
        }
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnOgrenciAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrenciAraActionPerformed
        String sql = "Select * from Ogrenciler where TCno=?";
        try {
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, txtOgrTc.getText());
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {  //veritabanımızı tek tek gezmeyi sağlar
                String ekle1 = resultSet.getString("TCNo");
                txtOgrTc.setText(ekle1);
                String ekle2 = resultSet.getString("AdSoyad");
                txtOgrAdSoyad.setText(ekle2);
                String ekle3 = resultSet.getString("Cinsiyet");
                txtCinsiyet.setText(ekle3);
                String ekle4 = resultSet.getString("Email");
                txtEmail.setText(ekle4);
                String ekle5 = resultSet.getString("TelNo");
                txtTelefonNo.setText(ekle5);
                resultSet.close();
                preparedStatement.close();
            } else {
                JOptionPane.showMessageDialog(null, "Öğrenci Bulunamadı");
                txtClear();
            }
        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, exception);
        } finally {
            try {
                resultSet.close();
                preparedStatement.close();
            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, exception);
            }

        }
    }//GEN-LAST:event_btnOgrenciAraActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        GeneralAppService.backActionAnaSayfa();
        setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        Admin admin = new Admin();
        admin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtOgrTcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOgrTcKeyReleased
        txtOgrAdSoyad.setText(null);
        txtCinsiyet.setText(null);
        txtEmail.setText(null);
        txtTelefonNo.setText(null);
    }//GEN-LAST:event_txtOgrTcKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgrenciSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgrenciSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgrenciSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgrenciSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OgrenciSil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOgrenciAra;
    private javax.swing.JButton btnSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCinsiyet;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOgrAdSoyad;
    private javax.swing.JTextField txtOgrTc;
    private javax.swing.JTextField txtTelefonNo;
    // End of variables declaration//GEN-END:variables
}
