
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adem_
 */
public class SifremiUnuttum extends javax.swing.JFrame {

    Connection connection;
    ResultSet resultSet;
    PreparedStatement preparedStatement;

    /**
     * Creates new form SifremiUnuttum
     */
    public SifremiUnuttum() {
        initComponents();
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 200));
        connection = DBConnect.getConnection();
    }

    //Tabloda tc kimlik numarasına göre arar bulursa kod gönderir.
    public void arama() {
        String aramaGirdi = txtTCNo.getText();
        String sql = "Select * from Yoneticiler where TCNo='" + aramaGirdi + "'";
        try {
            preparedStatement = connection.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                kodGonder(resultSet.getString(5));
                txtName.setText(resultSet.getString(3));
                txtSurname.setText(resultSet.getString(4));
                txtEmail.setText(resultSet.getString(5));
            } else {
                JOptionPane.showMessageDialog(null, "Hatalı Kullanıcı Adı Girildi");
                temizle();
            }
        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, exception);

        }
    }

    public void kodGonder(String mail) {
        MailAppService.sendMail(mail);
    }

    public void temizle() {
        txtTCNo.setText(null);
        txtName.setText(null);
        txtSurname.setText(null);
        txtEmail.setText(null);
        txtCode.setText(null);
        txtPass.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        btnSifremiGetir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTCNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAra = new javax.swing.JButton();
        txtSurname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnKodGonder = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)), "Şifremi Unuttum", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20), new java.awt.Color(0, 153, 51))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 206, 210, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Şifre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 247, -1, -1));

        txtPass.setEditable(false);
        txtPass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 244, 210, -1));

        btnSifremiGetir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSifremiGetir.setText("Şifremi Getir");
        btnSifremiGetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSifremiGetirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSifremiGetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 231, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("E-Mail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 169, -1, -1));

        txtTCNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtTCNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 43, 210, -1));

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 166, 210, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("TC Kimlik No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 46, -1, -1));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 86, 210, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Doğrulama Kodu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 209, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("İsim");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 89, -1, -1));

        btnAra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAra.setText("Ara ve Doğrulama Kodu Gönder");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });
        jPanel1.add(btnAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 230, -1));

        txtSurname.setEditable(false);
        txtSurname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 125, 210, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Soyisim");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 128, -1, -1));

        btnKodGonder.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKodGonder.setText("Yeni Doğrulama Kodu Gönder");
        btnKodGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKodGonderActionPerformed(evt);
            }
        });
        jPanel1.add(btnKodGonder, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 231, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 660, 290));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\as.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\exit.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\asd.png")); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel15.setMaximumSize(new java.awt.Dimension(35, 30));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\adem_\\Documents\\NetBeansProjects\\Kutuphane_Otomasyonu\\Images\\arkaplan-fotograflar-3.jpg")); // NOI18N
        jLabel7.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        setSize(new java.awt.Dimension(699, 371));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSifremiGetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSifremiGetirActionPerformed
        txtPass.setText(null);
        try {
            if (Integer.parseInt(txtCode.getText()) == MailAppService.kod) {
                txtPass.setText(resultSet.getString(6));
            } else {
                JOptionPane.showMessageDialog(null, "Hatalı Kullanıcı Doğrulaması");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Doğrulama Kodu istenilen formata uygun değil!");
        }

    }//GEN-LAST:event_btnSifremiGetirActionPerformed

    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
        arama();
    }//GEN-LAST:event_btnAraActionPerformed

    private void btnKodGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKodGonderActionPerformed
        try {
            kodGonder(resultSet.getString(5));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Kod Gönderilemedi!");
        }
    }//GEN-LAST:event_btnKodGonderActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        Admin admin = new Admin();
        admin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        Admin admin = new Admin();
        admin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SifremiUnuttum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnKodGonder;
    private javax.swing.JButton btnSifremiGetir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTCNo;
    // End of variables declaration//GEN-END:variables
}
